name: Action to Azure VM
on: 
  - workflow_dispatch
  # - push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Create file
        run: ssh -o StrictHostKeyChecking=no grodriguez@4.246.203.10 touch prueba

      #- name: Deploy to server
      #  run: bash deploy.sh
